[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
optimizer_runs = 200

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "@zetachain/contracts=lib/protocol-contracts/contracts",
    "@aave/contracts=lib/aave-v3-origin/src/contracts"
]

[fmt]
sort_imports = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
